# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BloccBetaAT1100Beta13 < Formula
  desc "CLI to use interact with the blocc ecosystem."
  homepage "https://github.com/stacc/blocc-cli-releases"
  version "1.10.0-beta.13"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.10.0-beta.13/blocc-beta_1.10.0-beta.13_darwin_amd64.tar.gz"
      sha256 "be11d4c60ad6d71a5cd57d77574579a1beaf45276b83879cc4166b85c9bb65ac"

      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.10.0-beta.13/blocc-beta_1.10.0-beta.13_darwin_arm64.tar.gz"
      sha256 "5b640195b6e73e54b43a63cafa862609fd36ea8d8d07222ef8825a0aa5267b16"

      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.10.0-beta.13/blocc-beta_1.10.0-beta.13_linux_amd64.tar.gz"
      sha256 "9dfd39f8bff6e75774c7a26dd2f03cdcc45f275ac1e86a42b474ff9a4d04e3f1"
      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.10.0-beta.13/blocc-beta_1.10.0-beta.13_linux_arm64.tar.gz"
      sha256 "6119f3bc2d72326bf51bbd816b2fb7aeb67110f8625123f36ec6d708368f0b7b"
      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
  end

  def caveats
    <<~EOS
      Beta version of blocc cli. May be unstable.
    EOS
  end

  test do
    system "#{bin}/blocc-beta"
  end
end
