# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BloccBetaAT180Beta6 < Formula
  desc "CLI to use interact with the blocc ecosystem."
  homepage "https://github.com/stacc/blocc-cli-releases"
  version "1.8.0-beta.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.6/blocc-beta_1.8.0-beta.6_darwin_amd64.tar.gz"
      sha256 "7ae846cac3ee24bfb5c9e5292b9bb37d820cd58ad52411b3982b952b5f52379a"

      def install
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.6/blocc-beta_1.8.0-beta.6_darwin_arm64.tar.gz"
      sha256 "a8a44bc6805033c1d031bc8eae0bae649acf1646f45b111a35b4cd7eb0e1b6fd"

      def install
        bin.install "blocc-beta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.6/blocc-beta_1.8.0-beta.6_linux_amd64.tar.gz"
      sha256 "c00f3cdb6fd9ef01072c47fbeed7c90b761f472730652cfb9dfeba1b8f905e92"
      def install
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.6/blocc-beta_1.8.0-beta.6_linux_arm64.tar.gz"
      sha256 "f981443e8baa822c36a2d5a5c9632f4f9849d1be22f43839d041ba3c1fdfc99e"
      def install
        bin.install "blocc-beta"
      end
    end
  end

  def caveats
    <<~EOS
      Beta version of blocc cli. May be unstable.
    EOS
  end

  test do
    system "#{bin}/blocc-beta"
  end
end
