# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BloccBetaAT1100Beta23 < Formula
  desc "CLI to use interact with the blocc ecosystem."
  homepage "https://github.com/stacc/blocc-cli-releases"
  version "1.10.0-beta.23"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.10.0-beta.23/blocc-beta_1.10.0-beta.23_darwin_amd64.tar.gz"
      sha256 "57c60cd0c68cf857fb18a39b18ea423cd8dc203a89788aaeb34bc411454031b1"

      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.10.0-beta.23/blocc-beta_1.10.0-beta.23_darwin_arm64.tar.gz"
      sha256 "acd4999ad098c5cddecd6337d221919623cd71aded5c26511fb6ca78e522cc91"

      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.10.0-beta.23/blocc-beta_1.10.0-beta.23_linux_amd64.tar.gz"
      sha256 "d2da2270d97ff6c0c3dba284c7f90ca094484e61b0eda3afa27e4b2d35ba2f59"
      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.10.0-beta.23/blocc-beta_1.10.0-beta.23_linux_arm64.tar.gz"
      sha256 "80da859e682d67214087c4c3367897d76248617f64618f24d2cfa610b9591439"
      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
  end

  def caveats
    <<~EOS
      Beta version of blocc cli. May be unstable.
    EOS
  end

  test do
    system "#{bin}/blocc-beta"
  end
end
