# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BloccBetaAT180Beta2 < Formula
  desc "CLI to use interact with the blocc ecosystem."
  homepage "https://github.com/stacc/blocc-cli-releases"
  version "1.8.0-beta.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.2/blocc-beta_1.8.0-beta.2_darwin_amd64.tar.gz"
      sha256 "40aad0d9d9e6d6cc6e72ce8bb1519a1e6785c2dc3f2562b71733c9cb7d8793a1"

      def install
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.2/blocc-beta_1.8.0-beta.2_darwin_arm64.tar.gz"
      sha256 "52a0db85151124f307961d1569b27b0f1f37d417556cc00b2f7eb56571664cb0"

      def install
        bin.install "blocc-beta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.2/blocc-beta_1.8.0-beta.2_linux_amd64.tar.gz"
      sha256 "28bf3dd60070aac321d55acb9e8e8e07f9ab8af09aee3d12a17cc9ae32175875"
      def install
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.2/blocc-beta_1.8.0-beta.2_linux_arm64.tar.gz"
      sha256 "1b8f06d9cf932b1033f435a61775c70f34b664dfa1186b6d50c95282180a422d"
      def install
        bin.install "blocc-beta"
      end
    end
  end

  def caveats
    <<~EOS
      Beta version of blocc cli. May be unstable.
    EOS
  end

  test do
    system "#{bin}/blocc-beta"
  end
end
