# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BloccBetaAT178Beta1 < Formula
  desc "CLI to use interact with the blocc ecosystem."
  homepage "https://github.com/stacc/blocc-cli-releases"
  version "1.7.8-beta.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.7.8-beta.1/blocc-beta_1.7.8-beta.1_darwin_amd64.tar.gz"
      sha256 "3c14f60c557fd4fa83461ca9473fc120c33af7924ef602ef587a927a2cffe955"

      def install
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.7.8-beta.1/blocc-beta_1.7.8-beta.1_darwin_arm64.tar.gz"
      sha256 "a0f4fb7223cf9c770bfa959ba67387cb46094a975be672f17ca78ec19d915fbd"

      def install
        bin.install "blocc-beta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.7.8-beta.1/blocc-beta_1.7.8-beta.1_linux_amd64.tar.gz"
      sha256 "15941b198b65990c710994656abd5b5681ed54fb61cf9ecf4c3c09399c00d154"
      def install
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.7.8-beta.1/blocc-beta_1.7.8-beta.1_linux_arm64.tar.gz"
      sha256 "39d95f91530c15c3774b127e4af2841a4569d848d4ecbb8da979457211e5e408"
      def install
        bin.install "blocc-beta"
      end
    end
  end

  def caveats
    <<~EOS
      Beta version of blocc cli. May be unstable.
    EOS
  end

  test do
    system "#{bin}/blocc-beta"
  end
end
