# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BloccBetaAT190Beta4 < Formula
  desc "CLI to use interact with the blocc ecosystem."
  homepage "https://github.com/stacc/blocc-cli-releases"
  version "1.9.0-beta.4"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.9.0-beta.4/blocc-beta_1.9.0-beta.4_darwin_amd64.tar.gz"
      sha256 "dd1902c00f36e0d522efddc96b213c9890066fc8b474bb34f857a3abf034eea8"

      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.9.0-beta.4/blocc-beta_1.9.0-beta.4_darwin_arm64.tar.gz"
      sha256 "82443bde6c03e142adc6e031d79f203e7f6d5a7c5e42f08e5af7744554351ef4"

      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.9.0-beta.4/blocc-beta_1.9.0-beta.4_linux_amd64.tar.gz"
      sha256 "44c5359bbfac5b3eaebcc46892787ca0117eef4e5362b974e7369c8dae264333"
      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.9.0-beta.4/blocc-beta_1.9.0-beta.4_linux_arm64.tar.gz"
      sha256 "ab3c47051c323ef1a20406b02af1f5c6b33a69f132fbd5db20ec967d4c83ef99"
      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
  end

  def caveats
    <<~EOS
      Beta version of blocc cli. May be unstable.
    EOS
  end

  test do
    system "#{bin}/blocc-beta"
  end
end
