# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BloccBetaAT180Beta26 < Formula
  desc "CLI to use interact with the blocc ecosystem."
  homepage "https://github.com/stacc/blocc-cli-releases"
  version "1.8.0-beta.26"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.26/blocc-beta_1.8.0-beta.26_darwin_amd64.tar.gz"
      sha256 "5d1e457e03ad0e3a92b97a0ad37d1e6aad1ae544c5ad698fa517399245efa9fa"

      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.26/blocc-beta_1.8.0-beta.26_darwin_arm64.tar.gz"
      sha256 "6102098763f887b7411724e38d64fc732a392091fd77ab0df1b8d9f281a08c67"

      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.26/blocc-beta_1.8.0-beta.26_linux_amd64.tar.gz"
      sha256 "49a07484bfa335e176d1e4021a5382c54684de55c7b1b8811046bdc80f85a631"
      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.26/blocc-beta_1.8.0-beta.26_linux_arm64.tar.gz"
      sha256 "74cbdb6012887c3b5f24c4fca92fe2bd3c9653af3665b3990577ade2f0e5e92d"
      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
  end

  def caveats
    <<~EOS
      Beta version of blocc cli. May be unstable.
    EOS
  end

  test do
    system "#{bin}/blocc-beta"
  end
end
