# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BloccBetaAT180Beta23 < Formula
  desc "CLI to use interact with the blocc ecosystem."
  homepage "https://github.com/stacc/blocc-cli-releases"
  version "1.8.0-beta.23"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.23/blocc-beta_1.8.0-beta.23_darwin_amd64.tar.gz"
      sha256 "e6339e5751a87c942a5e1dc5069ad4d398c1f89e2832edb70695c9813ecbcffd"

      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.23/blocc-beta_1.8.0-beta.23_darwin_arm64.tar.gz"
      sha256 "0c84eef202b3d2849d6d676b39d7cc91fdbf8c0a7424e84ee1907d8e3d0ee318"

      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.23/blocc-beta_1.8.0-beta.23_linux_amd64.tar.gz"
      sha256 "5e1ca4a4a1aa808a26971b23bd170b8c89226134420fea882e4d8dcd76eaf9b2"
      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.23/blocc-beta_1.8.0-beta.23_linux_arm64.tar.gz"
      sha256 "3a6f01f7dbbfb2dee49a1810d9506f76531c63f7bea55c56c4d2c213bf59a761"
      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
  end

  def caveats
    <<~EOS
      Beta version of blocc cli. May be unstable.
    EOS
  end

  test do
    system "#{bin}/blocc-beta"
  end
end
