# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BloccBetaAT190Beta1 < Formula
  desc "CLI to use interact with the blocc ecosystem."
  homepage "https://github.com/stacc/blocc-cli-releases"
  version "1.9.0-beta.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.9.0-beta.1/blocc-beta_1.9.0-beta.1_darwin_amd64.tar.gz"
      sha256 "679acde106273484c6453356b00dc1d952cbbbfc612d73b58271c21333f28bc0"

      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.9.0-beta.1/blocc-beta_1.9.0-beta.1_darwin_arm64.tar.gz"
      sha256 "0189d692716be17c7f07c9a79184e6d4acc7003db42367f0bb457ac27b721802"

      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.9.0-beta.1/blocc-beta_1.9.0-beta.1_linux_amd64.tar.gz"
      sha256 "5bb795a82b3939d5d1d28bdbdd676fe7d6d8a833110579315c18565e1776a0e6"
      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.9.0-beta.1/blocc-beta_1.9.0-beta.1_linux_arm64.tar.gz"
      sha256 "ea6409f1f3b07913ba1130d92eecb4a81b6674c648ed56da6045d6a210928850"
      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
  end

  def caveats
    <<~EOS
      Beta version of blocc cli. May be unstable.
    EOS
  end

  test do
    system "#{bin}/blocc-beta"
  end
end
