# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BloccBeta < Formula
  desc "CLI to use interact with the blocc ecosystem."
  homepage "https://github.com/stacc/blocc-cli-releases"
  version "1.8.0-beta.7"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.7/blocc-beta_1.8.0-beta.7_darwin_amd64.tar.gz"
      sha256 "f1b5becc45bddb3133467912d84a326be9c39d750f49b21d2db2388e5690f25a"

      def install
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.7/blocc-beta_1.8.0-beta.7_darwin_arm64.tar.gz"
      sha256 "07a331b9e10fdd949c28f88dc3c75ddf90a7795cee75b4d4c58322f4f1f26ba6"

      def install
        bin.install "blocc-beta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.7/blocc-beta_1.8.0-beta.7_linux_amd64.tar.gz"
      sha256 "09bc033a96d38659df5edcc488d4dbb128bd890bcf0f293c886c38152ddcaa57"
      def install
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.7/blocc-beta_1.8.0-beta.7_linux_arm64.tar.gz"
      sha256 "966dc5a29f111827a79bb98bd0e9a68ce0affeec7a8f90cae13b3bbfb0285dd0"
      def install
        bin.install "blocc-beta"
      end
    end
  end

  def caveats
    <<~EOS
      Beta version of blocc cli. May be unstable.
    EOS
  end

  test do
    system "#{bin}/blocc-beta"
  end
end
