# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BloccBetaAT190Beta7 < Formula
  desc "CLI to use interact with the blocc ecosystem."
  homepage "https://github.com/stacc/blocc-cli-releases"
  version "1.9.0-beta.7"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.9.0-beta.7/blocc-beta_1.9.0-beta.7_darwin_amd64.tar.gz"
      sha256 "785b59a44c714045cd5d5920c2d178423ace8395b1a5673c931c8fb3a90edb8f"

      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.9.0-beta.7/blocc-beta_1.9.0-beta.7_darwin_arm64.tar.gz"
      sha256 "d8a1ffcd3bd645ea32d72122b1b580ab508fd8af3e547cb8d71c2c19c748d8ef"

      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.9.0-beta.7/blocc-beta_1.9.0-beta.7_linux_amd64.tar.gz"
      sha256 "74ef168296747c696780d953a3d396998c96c43194049591f2624ab7d7586805"
      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.9.0-beta.7/blocc-beta_1.9.0-beta.7_linux_arm64.tar.gz"
      sha256 "606b4cebd8625ae38458ede25ac7b8c3f11866316c07152b0c961a6929ddbc91"
      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
  end

  def caveats
    <<~EOS
      Beta version of blocc cli. May be unstable.
    EOS
  end

  test do
    system "#{bin}/blocc-beta"
  end
end
