# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BloccBetaAT190Beta6 < Formula
  desc "CLI to use interact with the blocc ecosystem."
  homepage "https://github.com/stacc/blocc-cli-releases"
  version "1.9.0-beta.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.9.0-beta.6/blocc-beta_1.9.0-beta.6_darwin_amd64.tar.gz"
      sha256 "7ff26d0f608ef991e9b692e01b9eac4ff546b8a224fc9e0415120e684b06461c"

      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.9.0-beta.6/blocc-beta_1.9.0-beta.6_darwin_arm64.tar.gz"
      sha256 "a8bd24b807b83b75e1e1c4ae14d41860d074048dc884ac8683700b21dc3a4753"

      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.9.0-beta.6/blocc-beta_1.9.0-beta.6_linux_amd64.tar.gz"
      sha256 "153e876bbc2fc97fe1318078ab91e952b3288ccf0f5d54323992383e97b537c5"
      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.9.0-beta.6/blocc-beta_1.9.0-beta.6_linux_arm64.tar.gz"
      sha256 "a86bc158e925dd6a6ec9b7e7e887b3ba5850346bd594ef5fcd21c6b42da66b42"
      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
  end

  def caveats
    <<~EOS
      Beta version of blocc cli. May be unstable.
    EOS
  end

  test do
    system "#{bin}/blocc-beta"
  end
end
