# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BloccBeta < Formula
  desc "CLI to use interact with the blocc ecosystem."
  homepage "https://github.com/stacc/blocc-cli-releases"
  version "1.8.0-beta.21"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.21/blocc-beta_1.8.0-beta.21_darwin_amd64.tar.gz"
      sha256 "2cd764c32edcc0026a612bf342b82657eeed01a943075320279799f1e8619fe8"

      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.21/blocc-beta_1.8.0-beta.21_darwin_arm64.tar.gz"
      sha256 "48d07c42f8ab0ba00775422d4cf08cb2af1524051b4bd49032dad00531f9127a"

      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.21/blocc-beta_1.8.0-beta.21_linux_amd64.tar.gz"
      sha256 "193a8755c94035d590782549a581b72f0fbb077d0bb67e1bf1a148e0e04c9e1a"
      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.21/blocc-beta_1.8.0-beta.21_linux_arm64.tar.gz"
      sha256 "61d181867d1210fa6008f8fe3f6743ca1b6c4cb67bb393fe066f2dc54724e3a3"
      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
  end

  def caveats
    <<~EOS
      Beta version of blocc cli. May be unstable.
    EOS
  end

  test do
    system "#{bin}/blocc-beta"
  end
end
