# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BloccBetaAT180Beta12 < Formula
  desc "CLI to use interact with the blocc ecosystem."
  homepage "https://github.com/stacc/blocc-cli-releases"
  version "1.8.0-beta.12"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.12/blocc-beta_1.8.0-beta.12_darwin_amd64.tar.gz"
      sha256 "10a61312ab9808975bc3fe595708f649f1df4eab35ce21e925f481cd2b537125"

      def install
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.12/blocc-beta_1.8.0-beta.12_darwin_arm64.tar.gz"
      sha256 "516fe6901aa62c5ed1832f5f835ed52efaf1552ad1d8a6fc771696997f6016ea"

      def install
        bin.install "blocc-beta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.12/blocc-beta_1.8.0-beta.12_linux_amd64.tar.gz"
      sha256 "d5384650e3d825b399acb559ab5ee609831db751b970fcd84b9ff8415b1352dd"
      def install
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.12/blocc-beta_1.8.0-beta.12_linux_arm64.tar.gz"
      sha256 "4a0d95dfd34e4bd5929075579e4bce57bb12eccec66b0c50ddbbb71cebac1615"
      def install
        bin.install "blocc-beta"
      end
    end
  end

  def caveats
    <<~EOS
      Beta version of blocc cli. May be unstable.
    EOS
  end

  test do
    system "#{bin}/blocc-beta"
  end
end
