# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BloccBetaAT180Beta27 < Formula
  desc "CLI to use interact with the blocc ecosystem."
  homepage "https://github.com/stacc/blocc-cli-releases"
  version "1.8.0-beta.27"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.27/blocc-beta_1.8.0-beta.27_darwin_amd64.tar.gz"
      sha256 "1434641662c01a25689a22587f18f9393bcb9bf3aa8c29b90160fac10ed0128b"

      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.27/blocc-beta_1.8.0-beta.27_darwin_arm64.tar.gz"
      sha256 "4f866dded3e94a1efd113d68060e5fee7304beec757e7e3dd5c3e665124f72aa"

      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.27/blocc-beta_1.8.0-beta.27_linux_amd64.tar.gz"
      sha256 "659ba5fa0b1882e7053e3efe4814c44945c9e7e0239f2388e572975c99bbab7a"
      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.27/blocc-beta_1.8.0-beta.27_linux_arm64.tar.gz"
      sha256 "d7bac7d8d6ee18dc967c92cecbb081f86ac7576be10ed54eb45be73d3f502041"
      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
  end

  def caveats
    <<~EOS
      Beta version of blocc cli. May be unstable.
    EOS
  end

  test do
    system "#{bin}/blocc-beta"
  end
end
