# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BloccBetaAT1100Beta6 < Formula
  desc "CLI to use interact with the blocc ecosystem."
  homepage "https://github.com/stacc/blocc-cli-releases"
  version "1.10.0-beta.6"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.10.0-beta.6/blocc-beta_1.10.0-beta.6_darwin_amd64.tar.gz"
      sha256 "849b8127cc7d1bb690165fcb9e04c2095d4714a4c3938675175bd8dc4af6acb2"

      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.10.0-beta.6/blocc-beta_1.10.0-beta.6_darwin_arm64.tar.gz"
      sha256 "8e3efb9a7a2bb06e0bcf4e9370f947523e7fbf19b048140a7836fe179e58595c"

      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.10.0-beta.6/blocc-beta_1.10.0-beta.6_linux_amd64.tar.gz"
      sha256 "45e3347f5f6df90a2473edde01f8396ebc3bb61c55a47dd94b6d26f3c2041da9"
      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.10.0-beta.6/blocc-beta_1.10.0-beta.6_linux_arm64.tar.gz"
      sha256 "204f3f11a0e51d82553e5570cd4552d27d89ef2899c5a25df3499cdc3d2076ee"
      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
  end

  def caveats
    <<~EOS
      Beta version of blocc cli. May be unstable.
    EOS
  end

  test do
    system "#{bin}/blocc-beta"
  end
end
