# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BloccBetaAT180Beta18 < Formula
  desc "CLI to use interact with the blocc ecosystem."
  homepage "https://github.com/stacc/blocc-cli-releases"
  version "1.8.0-beta.18"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.18/blocc-beta_1.8.0-beta.18_darwin_amd64.tar.gz"
      sha256 "426109d8b3620ba034fa97e2e8b91aa236e8a5241e58c36521bf09078c69e5d7"

      def install
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.18/blocc-beta_1.8.0-beta.18_darwin_arm64.tar.gz"
      sha256 "edcd6bf842da2365840e4552f2f11c672941edc9d33be0654a7c81032232aa3e"

      def install
        bin.install "blocc-beta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.18/blocc-beta_1.8.0-beta.18_linux_amd64.tar.gz"
      sha256 "b59b0e1893620eb0a523e43e8a7544055f19354c64c8615df8c5eff15f8f22be"
      def install
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.18/blocc-beta_1.8.0-beta.18_linux_arm64.tar.gz"
      sha256 "9607f37f15deab824b08f366235c7d483d22ebf584e7fb2f2da4485ded8f5ee3"
      def install
        bin.install "blocc-beta"
      end
    end
  end

  def caveats
    <<~EOS
      Beta version of blocc cli. May be unstable.
    EOS
  end

  test do
    system "#{bin}/blocc-beta"
  end
end
