# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BloccBetaAT180Beta1 < Formula
  desc "CLI to use interact with the blocc ecosystem."
  homepage "https://github.com/stacc/blocc-cli-releases"
  version "1.8.0-beta.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.1/blocc-beta_1.8.0-beta.1_darwin_amd64.tar.gz"
      sha256 "169bed5022113018f0ec680a060a68b4528fb2f5523b5580163f46667af3128f"

      def install
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.1/blocc-beta_1.8.0-beta.1_darwin_arm64.tar.gz"
      sha256 "d603df3e7316ec1db87d32927e6883cc0d3ddf2cb0e1acdff37a0e4fd66b38f8"

      def install
        bin.install "blocc-beta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.1/blocc-beta_1.8.0-beta.1_linux_amd64.tar.gz"
      sha256 "ac5c76ee6aa662c377bd5fe10bb8f5eb3e50b69196e2cf42ebef3e4ef542e017"
      def install
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.1/blocc-beta_1.8.0-beta.1_linux_arm64.tar.gz"
      sha256 "2e10002e5e511b638e483587ae3dbfcdeee5ffa0b528c28c66ea2c8a4770c2a4"
      def install
        bin.install "blocc-beta"
      end
    end
  end

  def caveats
    <<~EOS
      Beta version of blocc cli. May be unstable.
    EOS
  end

  test do
    system "#{bin}/blocc-beta"
  end
end
