# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BloccBetaAT180Beta22 < Formula
  desc "CLI to use interact with the blocc ecosystem."
  homepage "https://github.com/stacc/blocc-cli-releases"
  version "1.8.0-beta.22"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.22/blocc-beta_1.8.0-beta.22_darwin_amd64.tar.gz"
      sha256 "5c80201e43efb1a13ca9aeb749c91f13502ad01a88934afd513793e807236490"

      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.22/blocc-beta_1.8.0-beta.22_darwin_arm64.tar.gz"
      sha256 "d28c05dd275e14047c07b3dc1ddc81dfb4136d11ae33305f025e49e9a93666dd"

      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.22/blocc-beta_1.8.0-beta.22_linux_amd64.tar.gz"
      sha256 "b30cc5c3cd4071cc026f9d04aecd0089b14efbfc24ee6fd7f7c0d67869e0979d"
      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.22/blocc-beta_1.8.0-beta.22_linux_arm64.tar.gz"
      sha256 "1e28267f390ff5c95245bb969502d9dd976d735eb6c42b75cf5edfebbe0207d9"
      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
  end

  def caveats
    <<~EOS
      Beta version of blocc cli. May be unstable.
    EOS
  end

  test do
    system "#{bin}/blocc-beta"
  end
end
