# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BloccBetaAT1100Beta8 < Formula
  desc "CLI to use interact with the blocc ecosystem."
  homepage "https://github.com/stacc/blocc-cli-releases"
  version "1.10.0-beta.8"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.10.0-beta.8/blocc-beta_1.10.0-beta.8_darwin_amd64.tar.gz"
      sha256 "e7e22859a9d3bc34b2bca710a78215b906e3c0132b54932a04edbe156e078c60"

      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.10.0-beta.8/blocc-beta_1.10.0-beta.8_darwin_arm64.tar.gz"
      sha256 "606320d7765bd0e02f42c7c525bfbdeea3002ff6de3a2e5c22d93b1a2143bfb9"

      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.10.0-beta.8/blocc-beta_1.10.0-beta.8_linux_amd64.tar.gz"
      sha256 "9a894960d28293cf8806774fc71f8e16adfad975f8439400e0e60775b6b96db2"
      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.10.0-beta.8/blocc-beta_1.10.0-beta.8_linux_arm64.tar.gz"
      sha256 "053d77ecf58e73836ef0b2d7fee4b082d675634ba675da959a85e7372fd835ea"
      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
  end

  def caveats
    <<~EOS
      Beta version of blocc cli. May be unstable.
    EOS
  end

  test do
    system "#{bin}/blocc-beta"
  end
end
