# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BloccBetaAT1100Beta7 < Formula
  desc "CLI to use interact with the blocc ecosystem."
  homepage "https://github.com/stacc/blocc-cli-releases"
  version "1.10.0-beta.7"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.10.0-beta.7/blocc-beta_1.10.0-beta.7_darwin_amd64.tar.gz"
      sha256 "b116588164c66058fd42fed504573abfa57795da0e134c5d400dc65aa76a00be"

      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.10.0-beta.7/blocc-beta_1.10.0-beta.7_darwin_arm64.tar.gz"
      sha256 "7ead41450d087aeb359c95060d1514a0d3a5d91ea72dea1a2fc9796cfd150675"

      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.10.0-beta.7/blocc-beta_1.10.0-beta.7_linux_amd64.tar.gz"
      sha256 "bfe99499741410411571e147205fe6bedd434098ad12b2c9c82ebb8d1e283064"
      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.10.0-beta.7/blocc-beta_1.10.0-beta.7_linux_arm64.tar.gz"
      sha256 "ee3f3662407b9316d6837e268ae6e022ca2d229652171d8074fde30da92aee4c"
      define_method(:install) do
        bin.install "blocc-beta"
      end
    end
  end

  def caveats
    <<~EOS
      Beta version of blocc cli. May be unstable.
    EOS
  end

  test do
    system "#{bin}/blocc-beta"
  end
end
