# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BloccBetaAT178Beta2 < Formula
  desc "CLI to use interact with the blocc ecosystem."
  homepage "https://github.com/stacc/blocc-cli-releases"
  version "1.7.8-beta.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.7.8-beta.2/blocc-beta_1.7.8-beta.2_darwin_amd64.tar.gz"
      sha256 "ec69b64d73dd5493a2e69918078b6ef95a9e1f1354d7e247a5c0be48a5807e1a"

      def install
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.7.8-beta.2/blocc-beta_1.7.8-beta.2_darwin_arm64.tar.gz"
      sha256 "c465d9c827886c9db0bf1a73411cce024f1674ccd1652800970c9a349d6a3a22"

      def install
        bin.install "blocc-beta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.7.8-beta.2/blocc-beta_1.7.8-beta.2_linux_amd64.tar.gz"
      sha256 "42180d976091147bc2659e4647782e1298d48d9c658272a4d37d3a6f0da0f262"
      def install
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.7.8-beta.2/blocc-beta_1.7.8-beta.2_linux_arm64.tar.gz"
      sha256 "28cde37f2c916c8d390bce774a6785aac28134344ca6f5f4477a81bb4b9f043d"
      def install
        bin.install "blocc-beta"
      end
    end
  end

  def caveats
    <<~EOS
      Beta version of blocc cli. May be unstable.
    EOS
  end

  test do
    system "#{bin}/blocc-beta"
  end
end
