# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BloccBeta < Formula
  desc "CLI to use interact with the blocc ecosystem."
  homepage "https://github.com/stacc/blocc-cli-releases"
  version "1.8.0-beta.9"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.9/blocc-beta_1.8.0-beta.9_darwin_amd64.tar.gz"
      sha256 "5c336112fff6030f226663c4e55a1192c2e35e1fbdff40d809771baef3f36db0"

      def install
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.9/blocc-beta_1.8.0-beta.9_darwin_arm64.tar.gz"
      sha256 "c35ea3fc9498dcea8e376e5b105d3cd02d6568461821eed1d3ff6044e11953f9"

      def install
        bin.install "blocc-beta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.9/blocc-beta_1.8.0-beta.9_linux_amd64.tar.gz"
      sha256 "3afeb5256f31a1469933abbb5034df6092350c5294a1eed7f25ae9f63984e083"
      def install
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.9/blocc-beta_1.8.0-beta.9_linux_arm64.tar.gz"
      sha256 "719f16d05f769079958c36376d35036b588cbeb65083964edba48044ed6c6f12"
      def install
        bin.install "blocc-beta"
      end
    end
  end

  def caveats
    <<~EOS
      Beta version of blocc cli. May be unstable.
    EOS
  end

  test do
    system "#{bin}/blocc-beta"
  end
end
