# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class BloccBetaAT180Beta17 < Formula
  desc "CLI to use interact with the blocc ecosystem."
  homepage "https://github.com/stacc/blocc-cli-releases"
  version "1.8.0-beta.17"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.17/blocc-beta_1.8.0-beta.17_darwin_amd64.tar.gz"
      sha256 "45a4fce0984ac4300a57315684236ee8fb63640fc88f8f4fb66c6042c5a82ea1"

      def install
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.17/blocc-beta_1.8.0-beta.17_darwin_arm64.tar.gz"
      sha256 "55724ee6a141396bc0876b79fe139b69e00dec9b3a0eecebb52ccf4e4fbb7220"

      def install
        bin.install "blocc-beta"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.17/blocc-beta_1.8.0-beta.17_linux_amd64.tar.gz"
      sha256 "9c5f28a5507cae44bfb8073648c37bf676967443591315e5a25b8b8bdc483021"
      def install
        bin.install "blocc-beta"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/blocc-cli-releases/releases/download/beta-cli-v1.8.0-beta.17/blocc-beta_1.8.0-beta.17_linux_arm64.tar.gz"
      sha256 "a14d0069f6517edee024440ee44447847e40c2522c6eef24a1eb077e1a801fd1"
      def install
        bin.install "blocc-beta"
      end
    end
  end

  def caveats
    <<~EOS
      Beta version of blocc cli. May be unstable.
    EOS
  end

  test do
    system "#{bin}/blocc-beta"
  end
end
