# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stacc < Formula
  desc "Software used to communicate with Stacc cloud environments"
  homepage "https://github.com/stacc/stacc-CLI"
  version "0.1.84"
  license "Apache-2.0"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/stacc/stacc-CLI/releases/download/v0.1.84/stacc_0.1.84_Darwin_x86_64.tar.gz"
    sha256 "c4ef9c44ed7ac278a22a9cabd90e08f461cad0db861527b11b87c72d77df02b9"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/stacc/stacc-CLI/releases/download/v0.1.84/stacc_0.1.84_Darwin_arm64.tar.gz"
    sha256 "58984dee07b9c5924af3d6c06a88d312371c6966fe19461ba9bcc54e934e6dc6"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/stacc/stacc-CLI/releases/download/v0.1.84/stacc_0.1.84_Linux_x86_64.tar.gz"
    sha256 "82995cc9b8a0f639376a3fc0ae578b1597e2b868d808b7dc5a57fb2f4b297aa8"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/stacc/stacc-CLI/releases/download/v0.1.84/stacc_0.1.84_Linux_arm64.tar.gz"
    sha256 "dd54349d44ab685ceb7c5b842137e7697351c6b750011ecedbe9a210af573889"
  end

  def install
    bin.install "stacc"
  end

  test do
    system "#{bin}/stacc"
  end
end
