# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Stacc < Formula
  desc "Software used to communicate with Stacc cloud environments"
  homepage "https://github.com/stacc/stacc-CLI"
  version "0.1.0"
  license "Apache-2.0"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/stacc/stacc-CLI/releases/download/v0.1.0/stacc_0.1.0_Darwin_x86_64.tar.gz"
    sha256 "3b13de78c1cdb8c1e1cef84a7722750514e5503cd052b3e0fd722ff0cba89e6d"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/stacc/stacc-CLI/releases/download/v0.1.0/stacc_0.1.0_Linux_x86_64.tar.gz"
    sha256 "e46e3dacd71c8a97b17d2e137a895d76ce29aa6a7a69e6525b543c2f30332d1f"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/stacc/stacc-CLI/releases/download/v0.1.0/stacc_0.1.0_Linux_arm64.tar.gz"
    sha256 "e34296edd0cd7055424aff7f49b2edbab5e173b214404941a9d38a286e38dcb8"
  end

  def install
    bin.install "stacc"
  end

  test do
    system "#{bin}/stacc"
  end
end
