# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StaccNext < Formula
  desc "Software used to communicate with Stacc cloud environments"
  homepage "https://github.com/stacc/cli"
  version "0.6.17"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacc/cli-next/releases/download/v0.6.17/stacc_0.6.17_Darwin_x86_64.tar.gz"
      sha256 "3e5d74091a26957a193fa93ca3822d19493f039669be6ff2d9cba4daaabca61f"

      def install
        bin.install "stacc"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacc/cli-next/releases/download/v0.6.17/stacc_0.6.17_Darwin_arm64.tar.gz"
      sha256 "338a82cd86e3d6fe097355f8b83202df55fc4e8de61a101638bf1c9ab5d09aa5"

      def install
        bin.install "stacc"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/cli-next/releases/download/v0.6.17/stacc_0.6.17_Linux_arm64.tar.gz"
      sha256 "7d43a732662c660b222bb3432b25a712088396c8c92889cd756ebe5c8b1a51cb"

      def install
        bin.install "stacc"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/stacc/cli-next/releases/download/v0.6.17/stacc_0.6.17_Linux_x86_64.tar.gz"
      sha256 "e710bfc9296eb80e9af2363b602513bcf91b08db3de6fa32d3415d66b0ca2e5b"

      def install
        bin.install "stacc"
      end
    end
  end

  conflicts_with "stacc/tap/stacc"

  def caveats; <<~EOS
    This formula is installed as 'stacc'
  EOS
  end

  test do
    system "#{bin}/stacc"
  end
end
