# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class StaccNext < Formula
  desc "Software used to communicate with Stacc cloud environments"
  homepage "https://github.com/stacc/cli"
  version "0.3.0"
  license "Apache-2.0"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/stacc/cli-next/releases/download/v0.3.0/stacc_0.3.0_Darwin_x86_64.tar.gz"
      sha256 "3bd8848ca56d82f3d52de2af4a290c43a46cc6280f70313c617741c5cbbae978"
    end
    if Hardware::CPU.arm?
      url "https://github.com/stacc/cli-next/releases/download/v0.3.0/stacc_0.3.0_Darwin_arm64.tar.gz"
      sha256 "61fe5be4513dc351b2fbd5e20afc660005f4c21c05cc36ef83a4f3d7bcf1c451"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/stacc/cli-next/releases/download/v0.3.0/stacc_0.3.0_Linux_x86_64.tar.gz"
      sha256 "42c4ede9a2a3dd3734c253cc51432d0cf54ec03820f7f494227eae19f9014602"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/stacc/cli-next/releases/download/v0.3.0/stacc_0.3.0_Linux_arm64.tar.gz"
      sha256 "d51176ace64228cbc3ffe8d8d5bce845113ef7f3cdf10fae23b6c36db2e95e31"
    end
  end

  conflicts_with "stacc/tap/stacc"

  def install
    bin.install "stacc"
  end

  def caveats; <<~EOS
    This formula is installed as 'stacc'
  EOS
  end

  test do
    system "#{bin}/stacc"
  end
end
